apiVersion: apps/v1
kind: Deployment
metadata:
  name: episodic-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episodic-app
  template:
    metadata:
      labels:
        app: episodic-app
    spec:
      containers:
      - name: episodic-app
        image: episodic-app:latest  # Have to replace
        ports:
        - containerPort: 8080
